### ISSUE TITLE
incompatible with DCC system

### ISSUE THREAD

**Issue by jmhnilbog** [ultrakorne/better-rolltables#173]
There's an assumption that all systems will have an 'npc' sheet class in the registerSettings() call that throws an error in the DCC system (where the npc sheet class is all-caps 'NPC').

I'd offer a PR fixing it but I'm not sure about the dnd5e assumptions in the code.

```
settingsConfig.js:20 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: better-rolltables]
    at Function.values (<anonymous>)
    at Settings.registerSettings (settingsConfig.js:20:35)
    at foundryReady (init.js:47:20)
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5547:11)
    at async Game._initializeGameView (foundry.js:6479:5)
    at async Game.initialize (foundry.js:5415:5)
```

**Comment by EricJohnAnderson** [comment]
This is also breaking HMGold  at the exact same position.  Which 5e package provides the npc object?

**Comment by duprel** [comment]
This is also true with Old School Essentials
